name: youtrack_api
description: "Typed client models and API abstractions for the YouTrack issue-tracking application."
version: 1.0.10

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
