import '../../domain/entities/custom_field.dart';
import '../../domain/entities/field_type.dart';
import '../../domain/repositories/custom_field_repository.dart';
import '../datasources/custom_field_remote_data_source.dart';
import '../models/custom_field_model.dart';

class CustomFieldRepositoryImpl implements CustomFieldRepository {
  final CustomFieldRemoteDataSource remoteDataSource;

  CustomFieldRepositoryImpl(this.remoteDataSource);

  @override
  Future<CustomField> createCustomField({
    required String projectId,
    required String name,
    String? description,
    required FieldType type,
    bool isPrivate = false,
  }) async {
    final model = CustomFieldModel(
      id: '', // Will be generated by Supabase
      projectId: projectId,
      name: name,
      description: description,
      type: type,
      isPrivate: isPrivate,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
    return await remoteDataSource.createField(model);
  }

  @override
  Future<List<CustomField>> getCustomFieldsByProject(String projectId) async {
    return await remoteDataSource.getFieldsByProject(projectId);
  }

  @override
  Future<bool> validateFieldNameUniqueness({
    required String projectId,
    required String name,
  }) async {
    return await remoteDataSource.isFieldNameUnique(projectId, name);
  }

  @override
  Future<CustomField> updateCustomField({
    required String fieldId,
    String? name,
    String? description,
    FieldType? type,
    bool? isPrivate,
  }) async {
    final existing = await remoteDataSource.getFieldById(fieldId);
    final updated = existing.copyWith(
      name: name ?? existing.name,
      description: description ?? existing.description,
      type: type ?? existing.type,
      isPrivate: isPrivate ?? existing.isPrivate,
      updatedAt: DateTime.now(),
    );
    return await remoteDataSource.updateField(updated);
  }

  @override
  Future<void> deleteCustomField(String fieldId) async {
    await remoteDataSource.deleteField(fieldId);
  }
}